### ISSUE TITLE
Request for Access to Benchmarks

### ISSUE THREAD

**Issue by mahi045** [tufts-ml/GRAPE-MUST#1]
Dear @panlybero 
I read your paper and find it very interesting. I was wondering if it would be possible to gain access to the Random Formulas and Graph Coloring benchmarks used in your experiments. Having these benchmarks would be extremely helpful for my work.

I would greatly appreciate any assistance you can provide. Thank you in advance for your help.

**Comment by panlybero** [comment]
Hey! Thank you for your interest in our work. I have uploaded some dataset generation code including for graph coloring and random formulas. Hopefully I will be able to update the repository with more content soon.

**Comment by mahi045** [comment]
Hi @panlybero 
Thank you for your prompt response! The information you provided is incredibly helpful. I look forward to seeing more content in the repository.
